#!/bin/bash

# Function to check disk usage with alert
check_disk_usage_fun() {
  disk_usage=$(df -h | awk '$NF=="/" {print $5}' | tr -d '%')

  if [[ "$disk_usage" -ge 80 ]]; then
    echo "WARNING: Disk usage is above 80%"
    echo "Warning: Disk usage exceeded 80%. Please take proper actions." | mail -s "Disk Usage Warning" -a "From: Monitor System" amrelabbasy2003@gmail.com 
  fi
 echo "Disk Usage: $disk_usage%"
}

# Function to check CPU usage
check_cpu_usage_fun() {
  cpu_usage=$(top -b -n1 | grep "Cpu(s)" | awk '{printf "%.2f\n", 100 - $8}')
  echo "CPU usage is: $cpu_usage%"
}

# Function to check memory usage
mem_usage_fun() {
  mem_usage=$(free -h | awk 'NR==2 {printf "Total: %s, Used: %s, Free: %s\n", $2, $3, $4}')
  echo "Memory Usage is : $mem_usage%"
}

# Function to check top 5 running processes
running_process_fun() {
  running_processes=$(ps -eo pid,user,%mem,comm | sort -nrk 3,3 | head -n 5)
  echo "Top 5 Running processes are:"
  echo "$running_processes"
}

# Main execution block
echo " =============== Start Reporting  =============== "

echo " =========  Disk Usage  ========= "
check_disk_usage_fun

echo " ========= Checking CPU Usage  ========= "
check_cpu_usage_fun

echo " =========  Memory Usage  ========= "
mem_usage_fun

echo " ========= Top 5 Process running  ========= "
running_process_fun

echo " =============== End Reporting  =============== "

